# Assignment 3

## Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

## Answer

In [3]:
import numpy as np

arr = np.arange(2, 50, 3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

## Answer

In [8]:
import numpy as np

list1 = list()
list2 = list()

for i in range(5):
    inp1 = int(input("Enter the values of List 1 :"))
    list1.append(inp1)
for i in range(5):
    inp2 = int(input("Enter the values of List 2 :"))
    list2.append(inp2)
    
arr1 = np.array(list1)
arr2 = np.array(list2)

arr = np.concatenate((arr1, arr2))

sorted_arr = np.sort(arr)

print(" ")
print("Concatenated Array: ",arr)
print(" ")
print("Sorted Array: ",sorted_arr)

Enter the values of List 1 :1
Enter the values of List 1 :3
Enter the values of List 1 :5
Enter the values of List 1 :7
Enter the values of List 1 :9
Enter the values of List 2 :2
Enter the values of List 2 :4
Enter the values of List 2 :6
Enter the values of List 2 :8
Enter the values of List 2 :10
 
Concatenated Array:  [ 1  3  5  7  9  2  4  6  8 10]
 
Sorted Array:  [ 1  2  3  4  5  6  7  8  9 10]


## Question 3

Write a code snippet to find the dimensions of a ndarray and its size.

## Answer

In [18]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
print("\nDimension of Array is: ",arr.ndim)
print("\nSize of Array is: ",arr.size)

# To find Dimension of Array use Array_Name.ndim
# To find Size of Array use Array_Name.size

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimension of Array is:  2

Size of Array is:  9


## Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

## Answer 

In [8]:
import numpy as np

a_1d = np.array([1,2,3,4,5,6,7,8,9])
a_2d = a_1d[:,np.newaxis]

print(a_1d)
print("Dimension of 1st array :",a_1d.ndim)
print("Shape of 1st array :",a_1d.shape)
print(" ")
print(a_2d)
print("Dimension of 2nd array :",a_2d.ndim)
print("Shape of 2nd array :",a_2d.shape)

[1 2 3 4 5 6 7 8 9]
Dimension of 1st array : 1
Shape of 1st array : (9,)
 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Dimension of 2nd array : 2
Shape of 2nd array : (9, 1)


## Question 5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

## Answer

In [12]:
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])

ver = np.vstack((arr1,arr2))
hor = np.hstack((arr1,arr2))

print("1st array")
print(arr1)
print(" ")
print("2nd array")
print(arr2)
print(" ")
print("Horizontal Stack: ")
print(hor)
print(" ")
print("Vertical Stack: ")
print(ver)

1st array
[[10 20]
 [30 40]]
 
2nd array
[[50 60]
 [70 80]]
 
Horizontal Stack: 
[[10 20 50 60]
 [30 40 70 80]]
 
Vertical Stack: 
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


## Question 6

How to get unique items and counts of unique items?

## Answer

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,1,3,5,7,9,1,3,5,7,9])
unique, count = np.unique(arr, return_counts = True)

print("Array             :",arr)
print("Unique Items      :",unique)
print("Unique Items Count:",count)

Array             : [1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 3 5 7 9 1 3 5 7 9]
Unique Items      : [1 2 3 4 5 6 7 8 9]
Unique Items Count: [4 2 4 2 4 2 4 2 4]
